[package]
name = "validated-data"
version.workspace = true
edition = "2024"
license.workspace = true

[lints]
workspace = true

[dependencies]
derive_more = { workspace = true, features = ["display"] }
mmap-guard.workspace = true
rkyv.workspace = true
self_cell.workspace = true
serde_json = { workspace = true, features = ["arbitrary_precision", "preserve_order"] }
validated-data-macros = { path = "../validated-data-macros" }

[dev-dependencies]
avdschema = { path = "../avdschema", default-features = false }
tempfile = "3.23.0"
